import sys
import json
import re
import shlex
import subprocess
from pathlib import Path
import click
from cliutils.tools import (
    GumPrompts,
    ConfigManager,
    SubprocessUtilities,
)

ASSETS_PATH = Path(__file__).parent.parent / "assets"

prompts = GumPrompts()
config_manager = ConfigManager()
subprocess_utils = SubprocessUtilities()

@click.command("pr-create")
@click.option('--ticket-only', '-to', is_flag=True, help="Create a pull request with only a ticket reference.")
def pr_create(ticket_only):
    """
    Opens a new draft pull request in the current repository.

    This command uses interactive prompting to generate a pull request title and body.

    The title of the pull request is then generated by the user. The body of the pull request
    is generated from a template file, which is stored in the cliutils package.

    If the pull request has a corresponding ticket, the ticket number will be added
    to the pull request title. If the pull request does not have a corresponding ticket,
    the pull request title will be generated from the branch name.
    """

    _, branch_name = _pull_branch_name()

    if branch_name == "main":
        print("You are on the main branch. Please create a new branch and try again.")
        sys.exit()

    team_tag = config_manager.config["general"]["team-tag"]
    ticket_reference, pr_header, cleaned_branch = _parse_ticket_from_branch(branch_name, team_tag)

    pr_title_default = _generate_pr_title_default(cleaned_branch)
    pr_title = prompts.gum_input("What Do You Want To Name This PR?", pr_title_default)

    pr_body_template = _resolve_template(ticket_only)
    pr_body_with_ticket = pr_body_template.replace("replace_ticket_ref", ticket_reference)
    pr_body = prompts.gum_write("What Did You Do?", pr_body_with_ticket)

    _submit_pr(pr_header, pr_title, pr_body)


def _parse_ticket_from_branch(branch_name: str, team_tag: str) -> tuple[str, str, str]:
    """Extract ticket reference and clean branch name for PR title generation."""
    ticket_pattern = rf"{team_tag}-(\d{{1,4}})"
    ticket_match = re.search(ticket_pattern, branch_name)

    if ticket_match:
        ticket_reference = ticket_match.group(0)
        pr_header = f"{ticket_reference}: "
        cleaned_branch = re.sub(rf".*{team_tag}-\d{{1,4}}-", "", branch_name)
    else:
        ticket_reference = ""
        pr_header = ""
        cleaned_branch = branch_name

    return ticket_reference, pr_header, cleaned_branch


def _resolve_template(ticket_only: bool) -> str:
    """Load the appropriate PR body template."""
    template_name = "data_dbt_ticket_only.md" if ticket_only else "data_dbt_verbose.md"
    template_path = ASSETS_PATH / "templates" / "pull_requests" / template_name
    return template_path.read_text()


def _submit_pr(pr_header: str, pr_title: str, pr_body: str) -> None:
    """Attempt to create a draft PR, falling back to a non-draft if needed."""
    escaped_body = shlex.quote(pr_body)
    full_title = f"{pr_header}{pr_title}"

    try:
        subprocess_utils.run(f"gh pr create --title '{full_title}' --body {escaped_body} --draft")
    except subprocess.CalledProcessError as error:
        print(f"Attempting to create pull request without --draft flag because of: {error}")
        try:
            subprocess_utils.run(f"gh pr create --title '{full_title}' --body {escaped_body}")
        except subprocess.CalledProcessError as err:
            print(f"Failed to create pull request because of: {err}")
            sys.exit()


def _generate_pr_title_default(branch_name: str) -> str:
    """Convert a branch name into a human-readable PR title."""
    protected_keywords = ["data-", "infra-", "spike-"]
    prepositions = _load_prepositions()

    keyword_match = next(
        (kw for kw in protected_keywords if kw in branch_name),
        ""
    )
    pr_heading = keyword_match.replace("-", " - ") if keyword_match else ""
    title_body = branch_name.replace(keyword_match, "").replace("-", " ")

    words = [w.title() if w not in prepositions else w for w in title_body.split()]
    return pr_heading + " ".join(words)


def _load_prepositions() -> list[str]:
    """Load the prepositions list used for PR title casing."""
    prepositions_file = ASSETS_PATH / "data" / "prepositions.json"
    with open(prepositions_file, "r", encoding="utf-8") as f:
        return json.load(f)


def _pull_branch_name() -> tuple[str, str]:
    return subprocess_utils.run_and_capture_output("git branch --show-current")
