import sys
import json
import re
import shlex
import subprocess
from pathlib import Path
import click # type: ignore
from cliutils.tools.cliutils_tools import CLIUtils

utils = CLIUtils()

@click.command("pr-create")
@click.option('--ticket-only', '-to', is_flag=True, help="Create a pull request with only a ticket reference.")
def pr_create(ticket_only):
    """
    Opens a new draft pull request in the current repository.

    This command uses interactive prompting to generate a pull request title and body.

    The title of the pull request is then generated by the user. The body of the pull request
    is generated from a template file, which is stored in the cliutils package.

    If the pull request has a corresponding ticket, the ticket number will be added
    to the pull request title. If the pull request does not have a corresponding ticket,
    the pull request title will be generated from the branch name.
    """

    config = utils.load_config()

    # Pull the git branch name from git and use it as a placeholder value
    git_branch = subprocess.run(
        ["git", "branch", "--show-current"],
        capture_output=True,
        text=True,
        check=True
    )
    git_pr_default = git_branch.stdout.strip()
    team_tag = config['general']['team-tag']
    ticket_match = re.search(rf"{team_tag}-(\d{{1,4}})", git_pr_default)
    if ticket_match:
        ticket_reference = ticket_match.group(0)
        pr_header = ticket_reference + ": "
        base_cleaned_pr_default = re.sub(rf".*{team_tag}-(\d{{1,4}}-)", "", git_pr_default)
    else:
        base_cleaned_pr_default = git_pr_default
        ticket_reference = ""
        pr_header = ""
    cleaned_pr_default = _generate_pr_title_default(base_cleaned_pr_default)
    pr_title = utils.gum_input("What Do You Want To Name This PR?", cleaned_pr_default)
    commands_dir = Path(__file__).parent
    template_dir = commands_dir.parent / "pull_request_templates"

    if ticket_only:
        template = "data_dbt_ticket_only.md"
    else:
        template = "data_dbt_verbose.md"
    template_file = template_dir / template
    pr_body_from_env = template_file.read_text()
    # Parse template file and look for 'replace_ticket_ref' and replace with pr_ticket_reference
    if pr_body_from_env.find("replace_ticket_ref") != -1:
        pr_body_from_env = pr_body_from_env.replace("replace_ticket_ref", ticket_reference)
    pr_body = utils.gum_write("What Did You Do?", pr_body_from_env)
    escaped_body = shlex.quote(pr_body)
    # handle special characters in pr_body that would cause in error
    try:
        cmd1 = f"gh pr create --title '{pr_header}{pr_title}' --body {escaped_body} --draft"
        subprocess.run(cmd1, shell=True, cwd=Path.cwd(), check=True)
    except subprocess.CalledProcessError as error:
        print(
            f"Attempting to create pull request without --draft flag "
            f"because of: {error}"
        )
        try:
            cmd2 = f"gh pr create --title '{pr_header}{pr_title}' --body {escaped_body}"
            subprocess.run(cmd2, shell=True, cwd=Path.cwd(), check=True)
        except subprocess.CalledProcessError as err:
            print(f"Failed to create pull request because of: {err}")
            sys.exit()

def _generate_pr_title_default(git_pr_default):
    protected_keywords = ["data-", "infra-", "spike-"]
    prepositions = _load_prepositions()
    keyword_search = re.search(rf"({'|'.join(protected_keywords)})", git_pr_default)
    if keyword_search:
        keyword_match = keyword_search.group(0)
        pr_heading = keyword_match.replace("-", " - ")
    else:
        keyword_match = ""
        pr_heading = ""
    pr_title_body = git_pr_default.replace(keyword_match, "")
    pr_title_body = pr_title_body.replace("-", " ")

    pr_title_list = pr_title_body.split(" ")
    words = [word.title() if word not in prepositions else word for word in pr_title_list]
    pr_title = " ".join(words)
    return pr_heading + pr_title

def _load_prepositions():
    prepositions_file = Path(__file__).parent.parent / "seeds" / "prepositions.json"
    with open(prepositions_file, "r", encoding="utf-8") as f:
        prepositions = json.load(f)
    return prepositions
