general:
  team-tag: "DSA"
  team-name: "Data Science & Analytics"
  raise-on-interrupt: true
  raise-on-escape: true
commits:
  conventional-commits:
    types:
      - Feat
      - Refactor
      - Fix
      - Docs
      - Style
      - Test
      - Chore
branches:
  branch-prefixes:
    - feature
    - hotfix
    - chore
    - docs
aws-info:
  s3-bucket-name: "s3://dsa-team-etl-dev"
  s3-dag-location: "s3://dsa-team-etl-dev/dags/"
  s3-plugins-location: "s3://dsa-team-etl-dev/dags/plugins/"
  dag-root: "dsa-dags/dags/"
  plugins-root: "dsa-dags/plugins/"
theme:
  name: "$TERMINAL_THEME"
excluded-commands:
  - __init__